import React, { useEffect, useState, useRef, useMemo } from 'react';
import useCardStore from '../../store/useCardStore';
import { getMechanism, buildElementParams, getDecorationSlots, INSTRUCTION_TEXT } from '../../generators/registry';
import { getElements } from '../../store/cardModel';
import { renderAssemblyMap, CIRCLED_NUMBERS } from '../../generators/assemblyMap';
import { PAPER_SIZES, PRINT } from '../../generators/constants';
import { createSVG, svgToString, getLineStyle, addPath, addRect, addText } from '../../generators/svgBuilder';
import { getContourPath, getBlobPath } from '../../utils/imageProcessor';
import UserArtUpload from './UserArtUpload';
import { ChevronLeft, ChevronRight } from 'lucide-react';
import '../../styles/preview.css';

export default function SVGPreview() {
  const { cardParams, isTyping, paperSize, colorMode, language, decorationMode, setDecorationMode, isGenerating, setGenerating, appMode, userArt } = useCardStore();
  // Page 1 (mechanism template) and pages 2..N (decorations) are generated by
  // two separate effects: the template is cheap/synchronous and must track
  // every parameter change (expert-mode sliders), while the decoration pages
  // involve a Pollinations image fetch + contour trace and must NOT re-run on
  // every slider tick — only when their inputs (slot sizes, prompt, mode)
  // actually change.
  const [mechPages, setMechPages] = useState([]); // [{ el: SVGSVGElement, str: string }]
  const [decoPages, setDecoPages] = useState([]); // [{ el, str }]
  const [currentPage, setCurrentPage] = useState(0);
  const containerRef = useRef(null);
  // Real SVGSVGElement references (not just serialized strings), kept around
  // so the PDF export can hand them to svg2pdf.js directly.
  const pageElementsRef = useRef([]);
  // Fingerprint of the last decoration generation's inputs; matching key =
  // skip regeneration entirely. Monotonic run id guards against a stale,
  // slower-finishing generation overwriting a newer one.
  const decoKeyRef = useRef(null);
  const decoRunIdRef = useRef(0);

  const pages = useMemo(
    () => (mechPages.length > 0 ? [...mechPages.map((p) => p.str), ...decoPages.map((p) => p.str)] : []),
    [mechPages, decoPages],
  );
  pageElementsRef.current =
    mechPages.length > 0 ? [...mechPages.map((p) => p.el), ...decoPages.map((p) => p.el)] : [];

  const paper = PAPER_SIZES[paperSize] || PAPER_SIZES.A4;
  const isColor = colorMode !== 'bw';

  // --- Pages 1..K: Mechanism Templates (synchronous, track every param change) ---
  // One template page per element (single-mechanism cards have exactly one),
  // plus an assembly-map page whenever there is more than one element.
  useEffect(() => {
    const els = getElements(cardParams);
    if (els.length === 0) {
      setMechPages([]);
      setDecoPages([]);
      decoKeyRef.current = null;
      decoRunIdRef.current += 1; // invalidate any in-flight decoration run
      return;
    }

    const pageEls = els.map((element, i) => {
      const mech = getMechanism(element.mechanism);
      let svg1;
      if (mech) {
        const params = buildElementParams(element, paperSize, colorMode, cardParams.theme);
        svg1 = mech.render(params).svg;
      } else {
        svg1 = createSVG(paper.width, paper.height);
        addText(svg1, paper.width / 2, paper.height / 2, '아직 지원되지 않는 메커니즘입니다.', 5, 'middle');
      }
      if (els.length > 1) {
        // Part number matching the assembly-map footprint labels — kept in the
        // outer waste margin (above the trim line) so it never prints on the card.
        addText(svg1, PRINT.MARGIN, PRINT.MARGIN - 1.2, `${CIRCLED_NUMBERS[i] || i + 1} 부품`, 3.5, 'start');
      }
      return svg1;
    });
    if (els.length > 1) {
      pageEls.push(renderAssemblyMap(els, paperSize, colorMode, cardParams.theme));
    }
    setMechPages(pageEls.map((el) => ({ el, str: svgToString(el) })));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cardParams, paperSize, colorMode]);

  // --- Pages 2..N+1: Themed Decoration (async, skipped unless inputs changed) ---
  useEffect(() => {
    if (!cardParams) return;

      // A mechanism can ask for more than one decoration image/guide (e.g.
      // A mechanism can ask for more than one decoration image/guide (e.g.
      // 'layered-stage' wants one per wall). getDecorationSlots() returns a
      // content-size hint per slot; every mechanism without an explicit
      // decorationSlots() definition falls back to today's single 100x100mm
      // slot, so this loop reduces to exactly the old single-page behavior
      // for them.
      const slots = getDecorationSlots(cardParams, paperSize, colorMode);

    // 'user-image' needs an uploaded drawing to work with; without one, fall
    // back to the freehand guide (the mode button is disabled anyway, this
    // guards races where the art is cleared while the mode is still set).
    const effectiveMode = decorationMode === 'user-image' && !userArt ? 'freehand' : decorationMode;

    // Slot dimensions are rounded to whole mm in the fingerprint so a slider
    // drag that nudges a resolver-derived slot by fractions of a mm doesn't
    // re-fetch images; anything that visibly changes the decoration pages
    // (prompt, theme, mode, paper, real size changes) does. The user-art hash
    // only participates while it's actually shown, so re-uploading a drawing
    // never invalidates AI/freehand pages.
    const decoKey = JSON.stringify({
      slots: slots.map((s) => ({ l: s.label, w: Math.round(s.width), h: Math.round(s.height) })),
      theme: cardParams.theme,
      imagePrompt: cardParams.imagePrompt,
      variants: cardParams.decorationVariants,
      decorationMode: effectiveMode,
      userArt: effectiveMode === 'user-image' ? `${userArt.length}:${userArt.slice(-40)}` : null,
      paperSize,
      colorMode,
    });
    if (decoKey === decoKeyRef.current) return;
    decoKeyRef.current = decoKey;
    const runId = decoRunIdRef.current + 1;
    decoRunIdRef.current = runId;

    const run = async () => {
      setGenerating(true);
      try {

      // Slot width/height are mm hints designed against an A4 (210mm-wide)
      // reference — the same ratio the original single 100mm hint used — so
      // a single 100x100 slot scales identically to the pre-existing
      // A4/Letter-proportional logic (no regression).
      const slotScale = Math.min(paper.width, paper.height) / 210;
      const maxDecoW = paper.width - 2 * PRINT.MARGIN;
      const maxDecoH = paper.height * (115 / 297);
      const titleY = paper.height * (65 / 297);
      const decoY = paper.height * (80 / 297);

      const decorationPages = await Promise.all(slots.map(async (slot, i) => {
        const svg = createSVG(paper.width, paper.height);

        // Fit this slot's aspect ratio proportionally to the paper, then
        // defensively clamp inside the printable area (guards against
        // unusually tall/wide slot hints from a mechanism).
        let decoW = slot.width * slotScale;
        let decoH = slot.height * slotScale;
        const fitScale = Math.min(1, maxDecoW / decoW, maxDecoH / decoH);
        decoW *= fitScale;
        decoH *= fitScale;
        const decoX = (paper.width - decoW) / 2;

        // Per-slot image prompt: an explicit decorationVariants[i] (see
        // api/chat.js for 'layered-stage') wins; otherwise fall back to the
        // single shared imagePrompt/theme exactly like before. When there
        // are multiple slots but no variant was supplied, append the slot's
        // own label as a distinguishing hint so the pages at least look
        // intentionally different — reusing the same image across slots in
        // that degraded case is acceptable, just never blank/erroring.
        const variant = cardParams.decorationVariants?.[i];
        const basePrompt = variant || cardParams.imagePrompt || cardParams.theme;
        const queryText = variant || (slots.length > 1 ? `${basePrompt} ${slot.label}` : basePrompt);
        const themeQuery = encodeURIComponent(`${queryText} simple cute cartoon vector isolated on pure white background for kids sticker`);
        const imgUrl = `https://image.pollinations.ai/prompt/${themeQuery}?width=512&height=512&nologo=true`;

        // Title suffix: preserve the exact old single-slot wording; only
        // switch to the per-slot label once there's more than one page.
        const titleSuffix = slots.length > 1 ? slot.label : '장식 조각';

        if (effectiveMode === 'user-image') {
          // The user's own uploaded drawing embedded as the cuttable page-2
          // artwork, with the same traced cut-contour treatment as 'ai-image'.
          // getContourPath stretches the source over the box it's given, so
          // aspect-fit the drawing into the slot first and hand the SAME
          // fitted rect to both the <image> and the tracer — otherwise the
          // cut line would drift off a non-square upload.
          const dims = await new Promise((resolve) => {
            const probe = new Image();
            probe.onload = () => resolve({ w: probe.naturalWidth, h: probe.naturalHeight });
            probe.onerror = () => resolve({ w: 1, h: 1 });
            probe.src = userArt;
          });
          let artW = decoW;
          let artH = decoH;
          if (dims.w / dims.h > decoW / decoH) {
            artH = decoW * (dims.h / dims.w);
          } else {
            artW = decoH * (dims.w / dims.h);
          }
          const artX = decoX + (decoW - artW) / 2;
          const artY = decoY + (decoH - artH) / 2;

          const img = document.createElementNS('http://www.w3.org/2000/svg', 'image');
          img.setAttribute('href', userArt);
          img.setAttribute('x', artX);
          img.setAttribute('y', artY);
          img.setAttribute('width', artW);
          img.setAttribute('height', artH);
          svg.appendChild(img);

          const contourPath = await getContourPath(userArt, artX, artY, artW, artH, 5);
          addPath(svg, contourPath, getLineStyle('CUT', isColor));

          addText(svg, paper.width / 2, titleY, `[ ${cardParams.theme} ] 내 그림 ${titleSuffix}`, 5, 'middle');
          addText(svg, paper.width / 2, paper.height * (195 / 297), '가위로 윤곽선을 따라 오린 후, 팝업 장치(풀칠 부위)에 붙여주세요!', 3, 'middle');
        } else if (effectiveMode === 'ai-image') {
          // Full-size AI image embedded as the actual cuttable artwork, with a
          // traced cut-contour around it.
          const img = document.createElementNS('http://www.w3.org/2000/svg', 'image');
          img.setAttribute('href', imgUrl);
          img.setAttribute('x', decoX);
          img.setAttribute('y', decoY);
          img.setAttribute('width', decoW);
          img.setAttribute('height', decoH);
          svg.appendChild(img);

          // Add contour cut line
          const contourPath = await getContourPath(imgUrl, decoX, decoY, decoW, decoH, 5);
          addPath(svg, contourPath, getLineStyle('CUT', isColor));

          addText(svg, paper.width / 2, titleY, `[ ${cardParams.theme} ] ${titleSuffix}`, 5, 'middle');
          addText(svg, paper.width / 2, paper.height * (195 / 297), '가위로 윤곽선을 따라 오린 후, 팝업 장치(풀칠 부위)에 붙여주세요!', 3, 'middle');
        } else {
          // 'freehand': a neutral placeholder outline the child draws inside,
          // annotated with size/position, plus a small AI image shown only
          // as an inspirational reference thumbnail (not meant to be cut).
          const freehandTitle = slots.length > 1
            ? `[ ${cardParams.theme} ] ${slot.label} 직접 그리기 가이드`
            : `[ ${cardParams.theme} ] 직접 그리기 가이드`;
          addText(svg, paper.width / 2, titleY, freehandTitle, 5, 'middle');

          // Neutral "draw inside this outline" placeholder cut-shape.
          const placeholderPath = getBlobPath(decoX, decoY, decoW, decoH);
          addPath(svg, placeholderPath, getLineStyle('CUT', isColor));

          const shapeCenterX = decoX + decoW / 2;
          const shapeBottom = decoY + decoH;

          // Dimension label just below the shape — outside the cut outline so
          // it never prints on the child's cut-out drawing.
          addText(svg, shapeCenterX, shapeBottom + 6, `${decoW.toFixed(0)}mm × ${decoH.toFixed(0)}mm`, 4, 'middle');

          // Position description in human terms, relative to the page center,
          // plus the exact mm offset for precision.
          const centerX = paper.width / 2;
          const centerY = paper.height / 2;
          const dx = shapeCenterX - centerX;
          const dy = decoY + decoH / 2 - centerY;
          const vertDesc = dy < -5 ? '위쪽' : dy > 5 ? '아래쪽' : '중앙';
          const horizDesc = dx < -5 ? '왼쪽' : dx > 5 ? '오른쪽' : '';
          const posDesc = `카드 중앙 ${vertDesc}${horizDesc ? ' ' + horizDesc : ''} (중심에서 x:${dx.toFixed(0)}mm, y:${dy.toFixed(0)}mm)`;
          addText(svg, shapeCenterX, shapeBottom + 12, posDesc, 3, 'middle');

          addText(svg, paper.width / 2, paper.height - PRINT.MARGIN - 8, '위 안내에 맞춰 자유롭게 그린 후, 그린 선을 따라 오려서 팝업 장치(풀칠 부위)에 붙여주세요!', 3, 'middle');

          // Small AI reference thumbnail — illustrative only, not cut geometry.
          // Sized well inside the print-safe margin so it never overlaps it.
          const thumbSize = 25;
          const thumbX = paper.width - PRINT.MARGIN - 10 - thumbSize;
          const thumbY = PRINT.MARGIN + 8;
          const thumbImg = document.createElementNS('http://www.w3.org/2000/svg', 'image');
          thumbImg.setAttribute('href', imgUrl);
          thumbImg.setAttribute('x', thumbX);
          thumbImg.setAttribute('y', thumbY);
          thumbImg.setAttribute('width', thumbSize);
          thumbImg.setAttribute('height', thumbSize);
          svg.appendChild(thumbImg);
          const dashedBorderStyle = { stroke: isColor ? '#888888' : '#555555', strokeWidth: 0.4, dasharray: '2 1', fill: 'none' };
          addRect(svg, thumbX, thumbY, thumbSize, thumbSize, dashedBorderStyle);
          addText(svg, thumbX + thumbSize / 2, thumbY + thumbSize + 4, '참고 예시', 2.5, 'middle');
          addText(svg, thumbX + thumbSize / 2, thumbY + thumbSize + 8, '(그대로 따라 그리지 않아도 돼요)', 2, 'middle');
        }

        return svg;
      }));

      if (runId !== decoRunIdRef.current) return;
      setDecoPages(decorationPages.map((el) => ({ el, str: svgToString(el) })));
      } finally {
        if (runId === decoRunIdRef.current) setGenerating(false);
      }
    };

    run();
    // No effect cleanup on purpose: a re-run whose fingerprint matches must
    // NOT cancel the in-flight generation (it would never be restarted). The
    // runId check above is the staleness guard instead.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cardParams, paperSize, colorMode, decorationMode, userArt]);

  // Keep the visible page index valid as the page list grows/shrinks.
  useEffect(() => {
    if (currentPage > 0 && currentPage >= pages.length) {
      setCurrentPage(Math.max(0, pages.length - 1));
    }
  }, [pages.length, currentPage]);

  useEffect(() => {
    if (containerRef.current && pages.length > 0) {
      containerRef.current.innerHTML = pages[currentPage];
    }
  }, [pages, currentPage]);

  const handleDownload = async () => {
    try {
      await runPdfDownload();
    } catch (err) {
      // Surface failures instead of letting the button silently "do nothing".
      console.error('[SVGPreview] PDF download failed:', err);
      alert('PDF를 만드는 중 문제가 발생했어요. 잠시 후 다시 시도해 주세요.');
    }
  };

  const runPdfDownload = async () => {
    const { exportAndDownload } = await import('../../generators/pdfExporter.js');
    const svgEls = pageElementsRef.current;
    if (!svgEls || svgEls.length === 0) return;

    // svg2pdf.js needs the elements attached to the document (and any
    // embedded raster images decoded) before it can read them correctly.
    const offscreen = document.createElement('div');
    offscreen.style.position = 'absolute';
    offscreen.style.left = '-9999px';
    offscreen.style.top = '0';
    offscreen.style.width = `${paper.width}mm`;
    offscreen.style.height = `${paper.height}mm`;
    offscreen.style.background = 'white';
    document.body.appendChild(offscreen);

    try {
      for (const svgEl of svgEls) {
        offscreen.appendChild(svgEl);
        const images = svgEl.querySelectorAll('image');
        for (const imageNode of images) {
          const href = imageNode.getAttribute('href') || imageNode.getAttribute('xlink:href');
          if (!href) continue;
          await new Promise((resolve) => {
            const tempImg = new Image();
            tempImg.crossOrigin = 'anonymous';
            tempImg.onload = resolve;
            tempImg.onerror = resolve;
            tempImg.src = href;
          });
        }
      }

      const els = getElements(cardParams);
      const parts = els
        .map((el, i) => ({ i, mech: getMechanism(el.mechanism) }))
        .filter((p) => p.mech && INSTRUCTION_TEXT[p.mech.instructionStyle])
        .map((p) => ({ ...p, txt: INSTRUCTION_TEXT[p.mech.instructionStyle] }));
      let instructions;
      if (parts.length === 1) {
        instructions = {
          title: `${cardParams.theme ? cardParams.theme + ' - ' : ''}${parts[0].txt.title}`,
          steps: parts[0].txt.steps,
          materials: parts[0].txt.materials,
          tips: parts[0].txt.tips,
        };
      } else if (parts.length > 1) {
        instructions = {
          title: `${cardParams.theme ? cardParams.theme + ' - ' : ''}조립 설명서 (부품 ${parts.length}개)`,
          materials: parts[0].txt.materials,
          steps: parts.flatMap((p) => [
            `[${CIRCLED_NUMBERS[p.i] || p.i + 1} ${p.mech.labelKo}]`,
            ...p.txt.steps,
          ]),
          tips: parts.map((p) => p.txt.tips).filter(Boolean).join(' · '),
        };
      }

      await exportAndDownload(
        svgEls,
        {
          paperSize,
          filename: `${cardParams.theme || 'popup'}_도안.pdf`,
          title: `${cardParams.theme || 'MyPopWorld'} Template`,
        },
        instructions,
        language
      );
    } finally {
      document.body.removeChild(offscreen);
    }
  };

  // SVG export — download each generated page as its own .svg file (vector,
  // editable in Illustrator/Inkscape/Figma). Flagged as a planned premium
  // feature (no gating exists yet anywhere in this app); freely usable for now.
  const handleSvgExport = () => {
    const svgEls = pageElementsRef.current;
    if (!svgEls || svgEls.length === 0) return;

    svgEls.forEach((svgEl, i) => {
      const svgString = svgToString(svgEl);
      const blob = new Blob([svgString], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${cardParams.theme || 'popup'}_도안_${i + 1}.svg`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    });
  };

  return (
    <div className="preview-content">
      <div className="decoration-mode-toggle">
        <span className="decoration-mode-label">장식 그리기 방식:</span>
        <button
          type="button"
          className={`decoration-mode-btn ${decorationMode === 'ai-image' ? 'active' : ''}`}
          onClick={() => setDecorationMode('ai-image')}
        >
          🎨 AI 이미지
        </button>
        <button
          type="button"
          className={`decoration-mode-btn ${decorationMode === 'freehand' ? 'active' : ''}`}
          onClick={() => setDecorationMode('freehand')}
        >
          ✏️ 내가 직접 그리기
        </button>
        <button
          type="button"
          className={`decoration-mode-btn ${decorationMode === 'user-image' ? 'active' : ''}`}
          disabled={!userArt}
          title={userArt ? undefined : '먼저 오른쪽 버튼으로 그림을 업로드하세요'}
          onClick={() => setDecorationMode('user-image')}
        >
          🖼️ 내 그림
        </button>
        <UserArtUpload />
      </div>
      <div className="svg-preview-container">
        {(isTyping || (isGenerating && appMode !== 'expert')) ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '16px', color: 'var(--text-secondary)' }}>
            <div className="spinner" style={{ width: '40px', height: '40px', borderWidth: '4px' }}></div>
            <div>{isGenerating ? '도안과 일러스트를 새로 그리고 있어요...' : 'AI가 도안과 일러스트를 열심히 설계하고 있어요...'}</div>
          </div>
        ) : pages.length === 0 ? (
          <div style={{ color: 'var(--text-secondary)' }}>
            {appMode === 'expert'
              ? '왼쪽에서 메커니즘을 선택하면 이곳에 도안이 표시됩니다.'
              : '채팅을 통해 만들고 싶은 작품을 결정하면 이곳에 도안이 표시됩니다.'}
          </div>
        ) : (
          <div className="svg-paper" ref={containerRef} style={{ width: `${paper.width}mm`, height: `${paper.height}mm` }}>
            {/* SVG injected here */}
          </div>
        )}
        {isGenerating && appMode === 'expert' && pages.length > 0 && (
          <div className="deco-generating-badge">장식 페이지 준비 중…</div>
        )}
      </div>

      {pages.length > 0 && !isTyping && !isGenerating && (
        <>
          <div className="page-navigator">
            <button
              className="btn-icon btn-secondary"
              aria-label="이전 페이지"
              disabled={currentPage === 0}
              onClick={() => setCurrentPage(p => p - 1)}
            >
              <ChevronLeft size={20} />
            </button>
            <div className="page-dots">
              {pages.map((_, i) => (
                <div key={i} className={`page-dot ${i === currentPage ? 'active' : ''}`} />
              ))}
            </div>
            <button
              className="btn-icon btn-secondary"
              aria-label="다음 페이지"
              disabled={currentPage === pages.length - 1}
              onClick={() => setCurrentPage(p => p + 1)}
            >
              <ChevronRight size={20} />
            </button>
          </div>

          <div className="download-overlay">
            <button
              className="btn-download"
              onClick={handleDownload}
            >
              PDF로 다운로드
            </button>
            <button
              className="btn-download-secondary"
              onClick={handleSvgExport}
              title="벡터 SVG 파일로 내보내기 (일러스트레이터/잉크스케이프 등에서 편집 가능)"
            >
              SVG로 내보내기
            </button>
          </div>
        </>
      )}
    </div>
  );
}
